### ISSUE TITLE
Fresh build breaks using boogi-cli on missing defaultColors.js

### ISSUE THREAD

**Issue by chrisblanch** [filipowm/BooGi#71]
Fresh install using the boogi cli, and I saw this error:

```
  ✖ Downloading BooGi ...
    → ENOENT: no such file or directory, stat '/Users/chris/Sites/nexttools/.boogi/v1.0.1/src/theme/defaultColors.js'
```

(Copying `colors.js` to `defaultColors.js` appears to get past it, but then I ran into a different issue about missing git commits?)

**Comment by wiebe** [comment]
This is because of boogi-cli not being updated with a change in how the color themes are defined. See https://github.com/filipowm/boogi-cli/issues/16

Just made a pull-request here: https://github.com/filipowm/boogi-cli/pull/17 (you can change this manually for now if you want to get up and going)

**Comment by bendtherules** [comment]
This is bad. Both the changes (in cli and main boogi) should have been done at the same time. Atleast now when it is baking installation for so many users, it should have been prioritised.

**Comment by filipowm** [comment]
Hi all,

I just came from vacation and merged the fix immediately. Thanks @wiebe for contribution. I will release fixed version today.
