### ISSUE TITLE
pathPrefix makes problems on link URLs.

### ISSUE THREAD

**Issue by mingry** [filipowm/BooGi#90]
When I set a pathPrefix in config.yml and build with --prefix-paths option, link URLs in the site make problems. 

1. The pathPrefix is inserted TWICE in the link URL generated from a mdx link. 

For example, if the mdx link was written as "(aaa)[bbb.pdf]" and the pathPrefix was set to "/~me", then the generated URL becomes like
            "www.example.com/~me/~me/bbd.pdf"

2. The URL of a static asset file does not include the pathPrefix. 

I could avoid the problems ad-hocly, but hope to be fixed in the next version.

**Comment by domarty** [comment]
Another pathPrefix issue: Normally, the left rail expands on click.  That no longer happens when deployed to production with a pathPrefix; the result is that the user can't see any subpages.
